### ISSUE TITLE
Cron job run every three (or n) days? 

### ISSUE THREAD

**Issue by LeafDuan** [HangfireIO/Cronos#9]
I want to run a job every three or five (or n) days from now, and I wrote the expression '0 8 */5 * *'.

If now is '2018/05/17',

and I get the occurrences:
```
0 8 */5 * *
2018/5/21 8:00:00
2018/5/26 8:00:00
2018/5/31 8:00:00
2018/6/1 8:00:00
2018/6/6 8:00:00
2018/6/11 8:00:00
2018/6/16 8:00:00
2018/6/21 8:00:00
2018/6/26 8:00:00
2018/7/1 8:00:00
2018/7/6 8:00:00
2018/7/11 8:00:00
2018/7/16 8:00:00
2018/7/21 8:00:00
2018/7/26 8:00:00
2018/7/31 8:00:00
2018/8/1 8:00:00
2018/8/6 8:00:00
```
but, which I expected are: 

```
0 8 */5 * *
2018/5/22 8:00:00     -- wrong
2018/5/27 8:00:00     -- wrong
2018/6/1 8:00:00
2018/6/6 8:00:00
2018/6/11 8:00:00
2018/6/16 8:00:00
2018/6/21 8:00:00
2018/6/26 8:00:00
2018/7/1 8:00:00
2018/7/6 8:00:00
2018/7/11 8:00:00
2018/7/16 8:00:00
2018/7/21 8:00:00
2018/7/26 8:00:00
2018/7/31 8:00:00
2018/8/5 8:00:00      -- wrong
2018/8/10 8:00:00     -- wrong
```

Do the cron expression that I wrote is wrong?  Or the Cronos don't support this situation?

Any one help me?

Thanks, 
Leaf

**Comment by odinserj** [comment]
Cron expressions are never calculated based on the current time, so `May 21, 2018` date will always match the `0 8 */5 * *` expression, regardless you are asking to get ones since May 1, May 3, May 13, etc. You can consider Cron expressions as [regular expressions](https://en.wikipedia.org/wiki/Regular_expression), but for date/time values: their output is stable.

Simply speaking, every cron parsing algorithm looks like the following loop:

```csharp
var data = startDate;
while (date < endDate)
{
    if (IsMatch(date, cronExpression))
    {
        yield return date;
    }

    date = date.AddSeconds(1); // Or minutes
}
```

**Comment by LeafDuan** [comment]
Hi odinserj, 

Thank you for your comment.

And I catch the same idea with you, override the get occurrences loop, using `DateTime.AddDays` instead.
